### ISSUE TITLE
v10.6.3 auto-queue not working on Firefox

### ISSUE THREAD

**Issue by andreapavoni** [pixelcrisis/turnstyles#38]
Hi there!

first of all, thank you for this excellent browser extension. As stated in the title, since the upgrade to 1.6.x, auto-queue doesn't work anymore in Firefox (I haven't tried on other browsers).

I've already used this feature with previous versions, but it stopped working when the new 1.6.x came out. I did several attempts but none has worked.

I hope this issue gets solved soon or later, thank you in advance!

**Comment by Nilorawr** [comment]
Hi, 

There is a little bug somewhere that prevents the code from updating. Restting the plugin and adding all the personalisations should fix the problem.

**Comment by andreapavoni** [comment]
Hi @Nilorawr thank you for your quick reply. Unfortunately I already tried to reset the plugin several times, without any luck.

I tried one more time after your suggestion, but the problem is still there.

I've also tried to uninstall/reinstall the plugin from scratch. Same result.

At least for me, the plugin worked until v1.5.x

**Comment by Nilorawr** [comment]
Did some testing, for me its broken again aswell, but for others in the room it does work. I'll poke the Dev to try and see what might be the problem.

**Comment by Nilorawr** [comment]
Hi @andreapavoni 
Resetting the plugin, and putting my setting back as they were makes the plugin work as inteded again for me. 
Just to be sure: You did update the  the bot callout and Saved the line with the button?

**Comment by andreapavoni** [comment]
Hi @Nilorawr ,

yes, I did try several times, my last try (few minutes ago, before replying here) was:

- reset the plugin
- uninstall and reinstall
- configure the saved line and save it
- tried the line in a room

nothing happened.

thanks for your support anyway :-)

**Comment by Nilorawr** [comment]
@andreapavoni We have narrowed the problem down to the DJ handler. It's being worked on. When the problem is resolved( or looks like) I will comunicate this back to you. 

No problem, I'm just one of the Beta testers, so kinda limited in how much i can be of help. But helping is what i do ;-)

**Comment by andreapavoni** [comment]
Thank you so much @Nilorawr looking forward for good news ;-)

**Comment by andreapavoni** [comment]
I’m trying the beta bookmarklet, auto queue works again. Thank you!

(not closing it until the new version is officially out, maybe other people has same problem).
